### ISSUE TITLE
Download Buttons not working

### ISSUE THREAD

**Issue by shazooer** [sunlightlabs/opendatapoliciesdecoded#5]
http://staging.opendatapoliciesdecoded.sunlightfoundation.com/downloads/

Downloads (text, json and dictionary files 404 error. ) 

individual policy download links also not working. 
http://staging.opendatapoliciesdecoded.sunlightfoundation.com/Amherst,NY(2014)/

**Comment by loandy** [comment]
This issue should be addressed by commit 749a8646f5622d796883608e7eac5e39086120b0.  Closing for now.
